global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - alert.yml

scrape_configs:
  # Prometheus instance
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus:9090

  # Raspberry Pi nodes
- job_name: node_exporter
  scrape_interval: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - helium.springsurprise.com:9100
    - neon.springsurprise.com:9100
    - argon.springsurprise.com:9100
    - krypton.springsurprise.com:9100
    - xenon.springsurprise.com:9100
    - dns-02.springsurprise.com:9100
    - dns-03.springsurprise.com:9100

  # Synology (NAS) device
- job_name: synology
  metrics_path: /snmp
  static_configs:
    - targets:
      - hovercraft.springsurprise.com
  params:
    module: [synology]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: snmp_exporter:9116

- job_name: unpoller
  scrape_interval: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - unpoller:9130
