global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - alert.yml

# Scrapers for the various services are read in from the scrapers directory.
# Each scrape config is in a self-contained file. If a service is not necessary,
# you can simply remove it from the scrapers directory and restart Prometheus.
scrape_config_files:
  - /etc/prometheus/scrapers/*.yml

