{
 "title": "Synology NAS",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host:",
    "query": {
     "query": "label_values(systemStatus, instance)"
    }
   },
   {
    "name": "storageDevice",
    "label": "Storage Device:",
    "query": {
     "query": "label_values(storageIODevice, storageIODevice)"
    }
   },
   {
    "name": "ifName",
    "label": "Interface: ",
    "query": {
     "query": "label_values(ifName{job=\"synology\"}, ifName)"
    }
   },
   {
    "name": "lunName",
    "label": "iSCSI LUN:",
    "query": {
     "query": "label_values(iSCSILUNName, iSCSILUNName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "modelName{instance=\"$host\", job=\"synology\"}"
    },
    {
     "expr": "serialNumber{instance=\"$host\"}"
    },
    {
     "expr": "version{instance=\"$host\"}"
    },
    {
     "expr": "upgradeAvailable{instance=\"$host\"}"
    },
    {
     "expr": "1.8*temperature{instance=\"$host\"}+32"
    },
    {
     "expr": "systemStatus{instance=\"$host\"}"
    },
    {
     "expr": "systemFanStatus{instance=\"$host\"}"
    },
    {
     "expr": "cpuFanStatus{instance=\"$host\"}"
    },
    {
     "expr": "powerStatus{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ssCpuSystem{instance=\"$host\", job=\"synology\"}",
     "legendFormat": "System"
    },
    {
     "expr": "ssCpuUser{instance=\"$host\", job=\"synology\"}",
     "legendFormat": "User"
    },
    {
     "expr": "ssCpuIdle{instance=\"$host\", job=\"synology\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "memTotalReal{instance=\"$host\", job=\"synology\"}",
     "legendFormat": "RAM Avail"
    },
    {
     "expr": "memTotalReal{instance=\"$host\", job=\"synology\"} - memCached{instance=\"$host\", job=\"synology\"} - memBuffer{instance=\"$host\", job=\"synology\"}",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "memCached{instance=\"$host\", job=\"synology\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "memBuffer{instance=\"$host\", job=\"synology\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "memTotalSwap{instance=\"$host\", job=\"synology\"} - memAvailSwap{instance=\"$host\", job=\"synology\"}",
     "legendFormat": "Swap Used"
    },
    {
     "expr": "memTotalSwap{instance=\"$host\", job=\"synology\"}",
     "legendFormat": "Swap Avail"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "laLoadInt{instance=\"$host\", job=\"synology\", laNames=\"Load-1\"}  ",
     "legendFormat": "{{laNames}}"
    },
    {
     "expr": "laLoadInt{instance=\"$host\", job=\"synology\", laNames=\"Load-5\"}  ",
     "legendFormat": "{{laNames}}"
    },
    {
     "expr": "laLoadInt{instance=\"$host\", job=\"synology\", laNames=\"Load-15\"}  ",
     "legendFormat": "{{laNames}}"
    }
   ]
  },
  {
   "title": "Raid Volume Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "raidTotalSize-raidFreeSize", "legendFormat": "{{label_name}} Used" },
    { "expr": "raidFreeSize", "legendFormat": "{{label_name}} Available" },
    { "expr": "raidTotalSize", "legendFormat": "{{label_name}} Max" }
   ]
  },
  {
   "title": "Disk Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "diskID{instance=\"$host\"}"
    },
    {
     "expr": "diskModel{instance=\"$host\"}"
    },
    {
     "expr": "diskType{instance=\"$host\"}"
    },
    {
     "expr": "diskStatus{instance=\"$host\"}"
    },
    {
     "expr": "1.8*diskTemperature{instance=\"$host\"}+32"
    }
   ]
  },
  {
   "title": "Network Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "ifIndex{instance=\"$host\", job=\"synology\"}"
    },
    {
     "expr": "ifPhysAddress{instance=\"$host\", job=\"synology\"}"
    },
    {
     "expr": "ifSpeed{instance=\"$host\", job=\"synology\"}"
    },
    {
     "expr": "ifMtu{instance=\"$host\", job=\"synology\"}"
    },
    {
     "expr": "ifHCInOctets{instance=\"$host\", job=\"synology\"}"
    },
    {
     "expr": "ifHCOutOctets{instance=\"$host\", job=\"synology\"}"
    },
    {
     "expr": "ifAdminStatus{instance=\"$host\", job=\"synology\"}"
    },
    {
     "expr": "ifOperStatus{instance=\"$host\", job=\"synology\"}"
    },
    {
     "expr": "ifPromiscuousMode{instance=\"$host\", job=\"synology\"}"
    }
   ]
  },
  {
   "title": "Network Details ($ifName)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "repeat": "ifName",
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Traffic ($ifName)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"$host\", job=\"synology\", ifName=\"$ifName\"}[5m])",
     "legendFormat": "Octets Rx"
    },
    {
     "expr": "irate(ifHCOutOctets{instance=\"$host\", job=\"synology\", ifName=\"$ifName\"}[5m])",
     "legendFormat": "Octets Tx"
    }
   ]
  },
  {
   "title": "Network Errors ($ifName)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(ifInDiscards{instance=\"$host\", job=\"synology\", ifName=\"$ifName\"}[5m])",
     "legendFormat": "Discards Rx"
    },
    {
     "expr": "irate(ifInErrors{instance=\"$host\", job=\"synology\", ifName=\"$ifName\"}[5m])",
     "legendFormat": "Errors Rx"
    },
    {
     "expr": "irate(ifOutDiscards{instance=\"$host\", job=\"synology\", ifName=\"$ifName\"}[5m])",
     "legendFormat": "Discards Tx"
    },
    {
     "expr": "irate(ifOutErrors{instance=\"$host\", job=\"synology\", ifName=\"$ifName\"}[5m])",
     "legendFormat": "Errors Tx"
    }
   ]
  },
  {
   "title": "Unicast Traffic ($ifName)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(ifInUcastPkts{instance=\"$host\", job=\"synology\", ifName=\"$ifName\"}[5m])",
     "legendFormat": "Packets Rx"
    },
    {
     "expr": "irate(ifOutUcastPkts{instance=\"$host\", job=\"synology\", ifName=\"$ifName\"}[5m])",
     "legendFormat": "Packets Tx"
    }
   ]
  },
  {
   "title": "Broadcast & Multicast Traffic ($ifName)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInBroadcastPkts{instance=\"$host\", job=\"synology\", ifName=\"$ifName\"}[5m])",
     "legendFormat": "Broadcast Rx"
    },
    {
     "expr": "irate(ifHCInMulticastPkts{instance=\"$host\", job=\"synology\", ifName=\"$ifName\"}[5m])",
     "legendFormat": "Multicast Rx"
    },
    {
     "expr": "irate(ifHCOutBroadcastPkts{instance=\"$host\", job=\"synology\", ifName=\"$ifName\"}[5m])",
     "legendFormat": "Broadcast Tx"
    },
    {
     "expr": "irate(ifHCOutMulticastPkts{instance=\"$host\", job=\"synology\", ifName=\"$ifName\"}[5m])",
     "legendFormat": "Multicast Tx"
    }
   ]
  },
  {
   "title": "Storage Device Details ($storageDevice)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 },
   "repeat": "storageDevice",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Load Average (1m)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storageIOLA1{instance=\"$host\", job=\"synology\", storageIODevice=\"$storageDevice\"}"
      }
     ]
    },
    {
     "title": "Load Average (5m)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storageIOLA5{instance=\"$host\", job=\"synology\", storageIODevice=\"$storageDevice\"}"
      }
     ]
    },
    {
     "title": "Load Average (15m)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storageIOLA15{instance=\"$host\", job=\"synology\", storageIODevice=\"$storageDevice\"}"
      }
     ]
    },
    {
     "title": "Bytes Read",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storageIONReadX{instance=\"$host\", job=\"synology\", storageIODevice=\"$storageDevice\"}"
      }
     ]
    },
    {
     "title": "Bytes Written",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storageIONWrittenX{instance=\"$host\", job=\"synology\", storageIODevice=\"$storageDevice\"}"
      }
     ]
    },
    {
     "title": "Read Ops",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storageIOReads{instance=\"$host\", job=\"synology\", storageIODevice=\"$storageDevice\"}"
      }
     ]
    },
    {
     "title": "Write Ops",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storageIOWrites{instance=\"$host\", job=\"synology\", storageIODevice=\"$storageDevice\"}"
      }
     ]
    },
    {
     "title": "Device Throughput (bytes/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(storageIONReadX{instance=\"$host\", job=\"synology\", storageIODevice=\"$storageDevice\"}[1m])",
       "legendFormat": "Read"
      },
      {
       "expr": "rate(storageIONWrittenX{instance=\"$host\", job=\"synology\", storageIODevice=\"$storageDevice\"}[1m])",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Device Operations (iops)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(storageIOReads{instance=\"$host\", job=\"synology\", storageIODevice=\"$storageDevice\"}[1m])",
       "legendFormat": "Read"
      },
      {
       "expr": "rate(storageIOWrites{instance=\"$host\", job=\"synology\", storageIODevice=\"$storageDevice\"}[1m])",
       "legendFormat": "Write"
      }
     ]
    }
   ]
  },
  {
   "title": "iSCSI ($lunName)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 },
   "repeat": "lunName",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "iSCSI Network Latency ($lunName)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "sum(iSCSILUNNetworkLatencyRx{instance=\"$host\", job=\"synology\"}) by (iSCSILUNInfoIndex) + on (iSCSILUNInfoIndex) group_left(iSCSILUNName) (0*iSCSILUNName{iSCSILUNName=\"$lunName\"})",
       "legendFormat": "Rx"
      },
      {
       "expr": "sum(iSCSILUNNetworkLatencyTx{instance=\"$host\", job=\"synology\"}) by (iSCSILUNInfoIndex) + on (iSCSILUNInfoIndex) group_left(iSCSILUNName) (0*iSCSILUNName{iSCSILUNName=\"$lunName\"})",
       "legendFormat": "Tx"
      }
     ]
    },
    {
     "title": "iSCSI Disk Latency ($lunName)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "max(iSCSILUNDiskLatencyRead{instance=\"$host\", job=\"synology\"}) by (iSCSILUNInfoIndex) + on (iSCSILUNInfoIndex) group_left(iSCSILUNName) (0*iSCSILUNName{iSCSILUNName=\"$lunName\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "max(iSCSILUNDiskLatencyWrite{instance=\"$host\", job=\"synology\"}) by (iSCSILUNInfoIndex) + on (iSCSILUNInfoIndex) group_left(iSCSILUNName) (0*iSCSILUNName{iSCSILUNName=\"$lunName\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "iSCSI IO ($lunName)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max(iSCSILUNIoSizeRead{instance=\"$host\", job=\"synology\"}) by (iSCSILUNInfoIndex) + on (iSCSILUNInfoIndex) group_left(iSCSILUNName) (0*iSCSILUNName{iSCSILUNName=\"$lunName\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "max(iSCSILUNIoSizeWrite{instance=\"$host\", job=\"synology\"}) by (iSCSILUNInfoIndex) + on (iSCSILUNInfoIndex) group_left(iSCSILUNName) (0*iSCSILUNName{iSCSILUNName=\"$lunName\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "iSCSI IOPs ($lunName)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "max(iSCSILUNIopsRead{instance=\"$host\", job=\"synology\"}) by (iSCSILUNInfoIndex) + on (iSCSILUNInfoIndex) group_left(iSCSILUNName) (0*iSCSILUNName{iSCSILUNName=\"$lunName\"})",
       "legendFormat": "Read IOPs"
      },
      {
       "expr": "max(iSCSILUNIopsWrite{instance=\"$host\", job=\"synology\"}) by (iSCSILUNInfoIndex) + on (iSCSILUNInfoIndex) group_left(iSCSILUNName) (0*iSCSILUNName{iSCSILUNName=\"$lunName\"})",
       "legendFormat": "Write IOPs"
      }
     ]
    }
   ]
  }
 ]
}