scrape_configs:
  # Synology (NAS) device
- job_name: synology
  metrics_path: /snmp
  static_configs:
    - targets:
      - 192.168.1.200
  params:
    module: [synology]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
      replacement: 'hovercraft.springsurprise.com'
    - target_label: __address__
      replacement: snmp_exporter:9116
